### ISSUE TITLE
Why doesn't Octo STS output the error detail?

### ISSUE THREAD

**Issue by suzuki-shunsuke** [octo-sts/app#246]
Hi, thank you for your great project!
I have a question about this app.

Some error messages of this App aren't helpful.
For example, when this App can't parse trust policy, the App outputs `Error: unable to parse trust policy found for "***"` but we can't understand why.

e.g.

```
Run octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
Error: unable to parse trust policy found for "foo"
```

<img width="581" alt="image" src="https://github.com/octo-sts/app/assets/13323303/174f2804-42d5-4a3e-a841-a678cb52419a">

I checked the source code then I found this App hides the error detail intentionally.

https://github.com/octo-sts/app/blob/1fc549c0973c27a9aba0257626d1903486dee2d9/pkg/octosts/octosts.go#L311-L315

> Don't leak the error to the client. 

But I'm not sure why.
Why does this App hide an error detail?
Do we need to hide Trust Policy from clients?

Error detail would be helpful for troubleshooting.

**Comment by mattmoor** [comment]
The policy may live in a private repo, and since we haven't authorized the caller we don't want to leak any data back to the caller.

@wlynch had some work to add a validating webhook for policies, which I think may have gotten closed when I moved this into its own org, but we should potentially revisit as a way to check things before they are merged into the repository vs. at STS time.

**Comment by suzuki-shunsuke** [comment]
Thank you for your quick answer!

> The policy may live in a private repo, and since we haven't authorized the caller we don't want to leak any data back to the caller.

I see. It makes sense.

> wlynch had some work to add a validating webhook for policies, which I think may have gotten closed when I moved this into its own org

Are you talking about this pull request?

- https://github.com/octo-sts/app/pull/144

> [wlynch](https://github.com/wlynch) closed this by deleting the head repository [on Mar 13](https://github.com/octo-sts/app/pull/144#event-12095708709)

**Comment by mattmoor** [comment]
Yeah that’s the one.

**Comment by wlynch** [comment]
Revived at https://github.com/octo-sts/app/pull/247!

**Comment by cpanato** [comment]
is this still an issue? @wlynch @suzuki-shunsuke

**Comment by suzuki-shunsuke** [comment]
Probably.

> wlynch had some work to add a validating webhook for policies, which I think may have gotten closed when I moved this into its own org, but we should potentially revisit as a way to check things before they are merged into the repository vs. at STS time.

https://github.com/octo-sts/app/pull/247 was closed but https://github.com/octo-sts/app/pull/285 was merged.
https://github.com/octo-sts/app/pull/285 was released at https://github.com/octo-sts/app/releases/tag/v0.3.0 .

> Add a webhook to validate trust policies by mattmoor in https://github.com/octo-sts/app/pull/285

I haven't tried the feature yet, though probably the issue was solved.

**Comment by cpanato** [comment]
i will close that for now, feel free to reopen or create a new one
