### ISSUE TITLE
Add support for customizing acceptable `aud`

### ISSUE THREAD

**Issue by mattmoor** [octo-sts/app#259]
Today you can't really customize the `aud` from most SSO flows.

Today this is checked here:
https://github.com/octo-sts/app/blob/1fc549c0973c27a9aba0257626d1903486dee2d9/pkg/octosts/octosts.go#L116-L118

We could check this here (and default to `octo-sts.dev`):
https://github.com/octo-sts/app/blob/1fc549c0973c27a9aba0257626d1903486dee2d9/pkg/octosts/trust_policy.go#L131-L134

**Comment by pdeslaur** [comment]
+1 - I could really use this for integration with Google's AppScript!
