### ISSUE TITLE
missing deployments permissions

### ISSUE THREAD

**Issue by chgr007** [octo-sts/app#471]
The app doesn't ask for deployment permissions, so I can't configure it in trust policies. I located the deployments permission in [github.InstallationPermissions](https://github.com/google/go-github/blob/master/github/apps.go)  , not sure why it's not registered. 
![image](https://github.com/user-attachments/assets/d34a9899-f524-418c-a02f-25774e8fe968)

**Comment by mattmoor** [comment]
We just haven’t configured the main app to ask for it, since it needs to request a superset of the permissions it issues.

**Comment by chgr007** [comment]
> We just haven’t configured the main app to ask for it, since it needs to request a superset of the permissions it issues.

Does that mean the permissions are limited to whatever is in the superset of permissions (which I guess is something that's defined by GH?) right now? Or is there a way we can configure it ourselves that I can bring forward to our platform team?

**Comment by mattmoor** [comment]
If you are operating your own, then it is something you'd configure in your own app's settings.

If you are consuming it via the public good instance we're operating (`octo-sts.dev`) then we'd have to toggle this.  I think we're receptive to this.  @cpanato was talking about how we might document a regular cadence for this, to minimize disruption to users.

**Comment by chgr007** [comment]
It would be really great if you could toggle it

**Comment by cpanato** [comment]
planned to update the permissions: https://github.com/octo-sts/app/issues/494

**Comment by cpanato** [comment]
this was applied last week
