### ISSUE TITLE
[Q3/2024 Permissions Updates] Update octo-sts permissions

### ISSUE THREAD

**Issue by cpanato** [octo-sts/app#494]
In Q3, we will update the octo-sts to add/remove permissions used when users request GH tokens.

### Adding:

- `deployment`
- `organization_projects`

### Removing

- none

We are planning to apply the changes on the week of ~~Sept/16~~ Sept/23 due to some extra load during the past week

**Comment by pdeslaur** [comment]
Would it also be possible to add the `organization_projects` permission to allow managing GitHub Projects?

**Comment by cpanato** [comment]
The `organization_projects` were already enabled. No actions on that

added `deployment`
